W4D4/music/config/routes.rb
Rails.application.routes.draw do
  resources :albums, except: [:new]
  resources :bands do
    resources :albums, only: :new
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
end

W4D4/music/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id           :bigint(8)        not null, primary key
#  band_id      :integer          not null
#  title        :string           not null
#  year         :integer          not null
#  live_version :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Album < ApplicationRecord

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band


end

W4D4/music/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album
end

W4D4/music/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  before_validation :ensure_session_token
  attr_reader :password

  validates :email, presence: true, uniqueness: true
  validates :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }


  def self.generate_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = self.find_by(email: email)
    if user && user.is_password?(password)
      user
    end
  end
end

W4D4/music/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])

    render :new
  end

  def edit
    @album = Album.find(params[:id])

    render :edit
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:success] = "Album successfully created"
      redirect_to album_url(@album)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  
  def update
    @album = Album.find(params[:id])
      if @album.update_attributes(album_params)
        flash[:success] = "Album was successfully updated"
        redirect_to album_url(@album)
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  def destroy
    @album= Album.find(params[:id])
    if @album.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to albums_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to new_band_album_url
    end
  end
  

  private
    def album_params
      params.require(:album).permit(:band_id, :title, :year, :live_version)
    end
end

W4D4/music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :log_in_user!

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token! if current_user
    session[:session_token] = nil
  end

  def current_user
    @user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(email)
    @user = User.find_by(email: email)
    session[:session_token] = @user.reset_session_token!
  end
end

W4D4/music/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new

    render :new
  end

  def edit
    @band = Band.find(params[:id])

    render :edit
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:success] = "Band successfully created"
      redirect_to band_url(@band)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  
  def update
    @band = Band.find(params[:id])
      if @band.update_attributes(band_params)
        flash[:success] = "Object was successfully updated"
        redirect_to band_url(@band)
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  def destroy
    @band = Band.find(params[:id])
    if @band.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to bands_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to bands_url
    end
  end
  

  private
    def band_params
      params.require(:band).permit(:name)
    end
end

W4D4/music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    @user.id = current_user.id

    if @user
      login!(@user)
      session[:session_token] = @user.reset_session_token!
      redirect_to user_url(@user)
    else
      redirect_to users_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W4D4/music/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      login!(@user)
      redirect_to users_url
    else
      redirect_to new_user_url
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to users_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to users_url
    end
  end
  

  private

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

W4D4/music/app/helpers/albums_helper.rb
module AlbumsHelper
end

W4D4/music/app/helpers/bands_helper.rb
module BandsHelper
end

W4D4/music/app/helpers/session_helper.rb
module SessionHelper
end

W4D4/music/app/helpers/sessions_helper.rb
module SessionsHelper
end

W4D4/music/app/helpers/users_helper.rb
module UsersHelper
end

W4D4/music/app/views/albums/_form.html.erb
<% action = (album.title.nil? ? albums_url : album_url(album) ) %>
<% post = ( album.persisted? ? :PATCH : :POST ) %>
<% submit = ( album.persisted? ? "Edit Album" : "Create Album" ) %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= post %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label for="band_id">Band Name:</label>
  <select id="band_id" name="album[band_id]">
  <% Band.all.each do |band| %>
    <option <%= "selected" if album.band_id == band.id %> value="<%= band.id %>" >
      <%= band.name %>
    </option>
  <% end %>
  </select>
  <label for="title">Album Title</label>
    <input type="text" id="title" name="album[title]" value="<%= album.title %>">
  <label for="year">Year</label>
    <input type="text" id="year" name="album[year]" value="<%= album.year %>">
  <label for="live_version">Live or Studio?</label>
    <input
      type="radio"
      id="live_version"
      name="album[live_version]"
      value="FALSE"
      <%= "checked" if ! album.live_version %>>Studio<br>
    <input
      type="radio"
      id="live_version"
      name="album[live_version]"
      value="TRUE"
      <%= "checked" if album.live_version %>>Live<br>

  <input type="submit" value="<%= submit %>">
</form>

W4D4/music/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

W4D4/music/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_band_album_url(band_id: 1) %>

W4D4/music/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

W4D4/music/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @album.title %></h3>

Year: <%= @album.year %><br>
Band: <%= @album.band_id %><br>
Version: <%= @album.live_version == "FALSE" ? "Studio" : "Live" %><br><br>

<%= link_to 'Edit', edit_album_url(@album) %> |
<%= link_to 'Back', albums_url%>
<%= link_to 'Destroy', @album, method: :delete, data: { confirm: 'Are you sure?' } %>

W4D4/music/app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url ) %>
<% method = (band.persisted? ? :patch : :post ) %>
<% submit = (band.name.nil? ? "Add Band" : "Edit Band" ) %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name">Band Name</label>
    <input type="text" id="name" name="band[name]" value="<%= band.name %>"><br>

  <input type="submit" value="<%= submit %>">

</form>

W4D4/music/app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

W4D4/music/app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bands</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

W4D4/music/app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form', band: @band %>

<%= link_to 'Back', bands_path %>

W4D4/music/app/views/bands/show.html.erb
<% albums = Album.all %>

<p id="notice"><%= notice %></p>


<h3><%= @band.name %></h3>
<br><br>

<h4>Albums:</h4>
<ul>
  <% albums.each do |album| %>
    <% if album.band_id == @band.id %>
    <li>
      <%= album.title %>
    </li>
    <% end %>
  <% end %>
</ul>


<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

W4D4/music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application.css" %>
  </head>
  <h1 font="ariel">Music App!</h1>

  <body>
  <% if logged_in? %>
    <%= current_user.email %>
    <form action="<%= session_url %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Sign Out">
    </form>
  <% else %>
    <a href="<%= new_session_url %>" background-color = aqua >Sign In</a>
    <a href="<%= new_user_url %>">Sign Up</a>
  <% end %>

    <%= yield %>
  </body>
</html>

W4D4/music/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

W4D4/music/app/views/users/edit.html.erb
<h1>Editing User</h1>

<form action="<%= user_url(@user) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <label for="email"></label>
    <input type="text" name="user[email]" id="email" value="<%= @user.email %>">
  <label for="password"></label>
    <input type="password" name="user[password]" id="password" value="<%= @user.password %>"><br>

  <input type="submit" value="Update User">
</form>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

W4D4/music/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

W4D4/music/app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">
  <label for="email">Email</label>
  <input type="text" id="email" name="user[email]">

  <label for="password">Password</label>
  <input type="password" id="password" name="user[password]"><br>

  <input type="submit" value="Create New User">
  <br><br>
</form>

<%= link_to 'Back', users_path %>

W4D4/music/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

Email: <%= @user.email %><br>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>